
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVE_H
#define TESTSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlave_Data;
extern INTEGER16 xPos;		/* Mapped at index 0x2000, subindex 0x00*/
extern INTEGER16 yPos;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 Pressed;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 cmd;		/* Mapped at index 0x2003, subindex 0x00*/

#endif // TESTSLAVE_H
